### ISSUE TITLE
in Ultra v0.1 - Length of the tap area of Home Apps isn't limited by the app Name

### ISSUE THREAD

**Issue by xhtmp** [tanujnotes/Ultra#4]
Please, limit the active tap area to launch the Home App to the length of its text name.

When I set the Home App in Ultra - the length of the tap area is not limited by the text name of a chosen app. The invisible active tap area after the name of the app is almost as long as the name of the app itself.

I am using live wallpaper with Ultra, so this issue prevents adequate interaction with the live wallpaper - because when I want to interact with the live wallpaper and tap on the Blank part of screen (After the text name of the app) - I launch my chosen Home app instead.

This issue appeares only in current Ultra v0.1 - there was no such problem with Olauncher Light v0.3

**Comment by tanujnotes** [comment]
This is will be fixed in the next update.
